<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Fili.MudAvalonia.Theme.UnitTests</RootNamespace>
    <AssemblyName>Fili.MudAvalonia.Theme.UnitTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fili.MudAvalonia.Theme\Fili.MudAvalonia.Theme.csproj" />
  </ItemGroup>

</Project>
