using Avalonia;
using Avalonia.Controls;
using Avalonia.Styling;
using Xunit;

namespace Fili.MudAvalonia.Theme.UnitTests;

/// <summary>
/// Pins the contract between the forked Simple templates and this package.
///
/// <para>
/// <c>Themes/Base/Controls</c> holds Avalonia's Simple templates verbatim. They paint from
/// resource keys they do not define, and <c>Themes/Base/Accents.axaml</c> is what supplies those
/// keys from Fili tokens. That handful of aliases is the entire reason forking Simple is cheaper
/// than writing 72 templates — and the entire thing that can silently break.
/// </para>
///
/// <para>
/// Silently is the operative word. The first standalone render looked fine until you noticed the
/// ToggleSwitches were labels with no switch: eighteen <c>*Color</c> keys had been missed while
/// their <c>*Brush</c> twins were mapped, and nothing anywhere reported a problem.
/// </para>
///
/// <para>
/// The list below is every key the forked templates reference but do not define, generated by
/// scanning them. <b>Regenerate it when upgrading Avalonia</b> — a new template that reaches for
/// a new key is exactly the upgrade hazard this guards.
/// </para>
/// </summary>
public class SimpleBridgeTests
{
    private static readonly string[] ContractKeys =
    [
        "CaptionButtonBackground", "CaptionButtonBorderBrush", "CaptionButtonForeground",
        "ContentControlThemeFontFamily", "DatePickerSpacerFill", "ErrorBrush",
        "FontSizeLarge", "FontSizeNormal", "FontSizeSmall",
        "HighlightBrush", "HighlightForegroundBrush", "HighlightForegroundColor",
        "HyperlinkVisitedBrush", "IconElementThemeHeight", "IconElementThemeWidth",
        "NotificationCardBackgroundBrush", "NotificationCardErrorBackgroundBrush",
        "NotificationCardInformationBackgroundBrush", "NotificationCardSuccessBackgroundBrush",
        "NotificationCardWarningBackgroundBrush",
        "RefreshVisualizerBackground", "RefreshVisualizerForeground",
        "ScrollBarThickness", "ScrollBarThumbThickness",
        "TextControlPlaceholderOpacity",
        "ThemeAccentBrush", "ThemeAccentBrush2", "ThemeAccentBrush3", "ThemeAccentBrush4",
        "ThemeAccentColor", "ThemeAccentColor2", "ThemeAccentColor3",
        "ThemeBackgroundBrush",
        "ThemeBorderHighBrush", "ThemeBorderHighColor",
        "ThemeBorderLowBrush", "ThemeBorderLowColor",
        "ThemeBorderMidBrush", "ThemeBorderMidColor", "ThemeBorderThickness",
        "ThemeControlHighBrush", "ThemeControlHighColor",
        "ThemeControlHighlightHighBrush", "ThemeControlHighlightLowBrush",
        "ThemeControlHighlightMidBrush", "ThemeControlHighlightMidColor",
        "ThemeControlLowBrush", "ThemeControlLowColor",
        "ThemeControlMidBrush", "ThemeControlMidColor",
        "ThemeControlMidHighBrush", "ThemeControlMidHighColor",
        "ThemeControlTransparentBrush", "ThemeControlVeryHighBrush",
        "ThemeDisabledColor", "ThemeDisabledOpacity",
        "ThemeForegroundBrush", "ThemeForegroundColor",
        "ThemeForegroundLowBrush", "ThemeForegroundLowColor", "ThemeForegroundMidColor",
        "TimePickerSpacerFill", "TitleBarBackgroundBrush",
    ];

    [Fact]
    public Task SimpleBridgeResolvesEveryKey() => UiThread.RunAsync(() =>
    {
        foreach (var variant in new[] { ThemeVariant.Light, ThemeVariant.Dark })
        {
            foreach (var key in ContractKeys)
            {
                Assert.True(
                    Application.Current!.TryFindResource(key, variant, out _),
                    $"The forked Simple templates reference '{key}' and nothing defines it under "
                        + $"{variant}. Controls painting from it will render wrong or not at all.");
            }
        }
    });

    /// <summary>
    /// The standalone base must actually supply templates. If SimpleControls failed to merge,
    /// every test above still passes — the tokens resolve fine — while no control has a template.
    /// </summary>
    [Theory]
    [InlineData(typeof(ComboBox))]
    [InlineData(typeof(ListBox))]
    [InlineData(typeof(TreeView))]
    [InlineData(typeof(ProgressBar))]
    [InlineData(typeof(Calendar))]
    public Task ForkedTemplatesAreReachable(Type controlType) => UiThread.RunAsync(() =>
    {
        Assert.True(
            Application.Current!.TryFindResource(controlType, ThemeVariant.Light, out var value),
            $"No ControlTheme for {controlType.Name}: the forked base did not merge.");

        Assert.IsType<ControlTheme>(value);
    });
}
