<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Fili.MudAvalonia.Theme.Gallery</RootNamespace>
    <AssemblyName>Fili.MudAvalonia.Theme.Gallery</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fili.MudAvalonia.Theme\Fili.MudAvalonia.Theme.csproj" />
  </ItemGroup>

</Project>
