using System.Text;

namespace Fili.MudAvalonia.Theme.UnitTests.Generation;

/// <summary>
/// Writes <c>Themes/Controls/Button.axaml</c>, and one marked region each in
/// <c>SplitButton.axaml</c> and <c>FiliTheme.axaml</c>, from ONE list of colours.
///
/// <para>
/// Three variants x eight colours x three states is a few hundred styles. Written by hand, one
/// colour's block can quietly differ from the others - and a typo in a resource key does not fail,
/// it resolves to nothing and leaves the default in place. Generated, every colour follows exactly
/// the same rule. <see cref="GeneratedThemeTests"/> fails when the files on disk differ from what
/// this would write, and rewrites them when <c>FILI_REGENERATE=1</c> is set.
/// </para>
/// </summary>
public static class ButtonThemeGenerator
{
    /// <summary>How the generated files name their source.</summary>
    public const string Name = "ButtonThemeGenerator";

    public const string SplitLabel = "split button variants, colours and sizes.";
    public const string TextLabel = "TextBlock colours.";

    private static readonly string[] Colours =
        ["Primary", "Secondary", "Tertiary", "Info", "Success", "Warning", "Error", "Dark"];

    private static readonly string[] States = [":pointerover", ":focus-visible", ":pressed"];

    /// <summary>Every generated file, as (path relative to the theme project, full content).</summary>
    public static IEnumerable<(string RelativePath, string Content)> Generate(string themeDirectory)
    {
        // Normalised because the raw string literals carry this source file's own line endings.
        yield return (ButtonPath, Normalise(Header + TextTheme() + OutlinedTheme() + FilledTheme() + Footer));

        foreach (var (path, label, body) in new[]
                 {
                     (SplitButtonPath, SplitLabel, SplitRegion()),
                     (FiliThemePath, TextLabel, TextBlockRegion()),
                 })
        {
            yield return (path, Patched(File.ReadAllText(Path.Combine(themeDirectory, path)), label, Normalise(body)));
        }
    }

    public static readonly string ButtonPath = Path.Combine("Themes", "Controls", "Button.axaml");
    public static readonly string SplitButtonPath = Path.Combine("Themes", "Controls", "SplitButton.axaml");
    public static readonly string FiliThemePath = "FiliTheme.axaml";

    /// <summary>The marker a hand-written file carries above the region this class owns.</summary>
    public static string Marker(string label) => $"<!-- GENERATED by {Name}: {label} -->";

    /// <summary>Line endings normalised to LF, which is how the files are generated and compared.</summary>
    public static string Normalise(string text) => text.Replace("\r\n", "\n");

    private static string Patched(string text, string label, string body)
    {
        text = Normalise(text);

        var start = text.IndexOf(Marker(label), StringComparison.Ordinal);
        if (start < 0)
        {
            throw new InvalidOperationException($"No '{Marker(label)}' marker to generate into.");
        }

        start = text.IndexOf('\n', start) + 1;
        var end = text.IndexOf("<!-- END GENERATED -->", start, StringComparison.Ordinal);
        end = text.LastIndexOf('\n', end) + 1;

        return text[..start] + body + text[end..];
    }

    // ---------------------------------------------------------------------------------------
    // Building blocks.
    // ---------------------------------------------------------------------------------------

    private static string Res(string key) => "{DynamicResource " + key + "}";

    private static string Style(string selector, params (string Property, string Value)[] setters)
    {
        var sb = new StringBuilder();
        sb.Append("    <Style Selector=\"").Append(selector).Append("\">\n");
        foreach (var (property, value) in setters)
        {
            sb.Append("      <Setter Property=\"").Append(property).Append("\" Value=\"").Append(value).Append("\" />\n");
        }

        return sb.Append("    </Style>\n").ToString();
    }

    /// <summary>_button.scss gives hover, :focus-visible and :active one value; :active is :pressed.</summary>
    private static string ButtonStates(string prefix, string part, string property, string value) =>
        string.Concat(States.Select(s => Style($"^{prefix}{s} /template/ Border#{part}", (property, value))));

    private static string Sizes(string small, string large) =>
        Style("^.small", ("Padding", small), ("FontSize", "13"))
        + Style("^.large", ("Padding", large), ("FontSize", "15"));

    private static string Template(bool shadow)
    {
        var sh = shadow ? "\n                BoxShadow=\"{DynamicResource FiliElevation2}\"" : "";

        return """
    <Setter Property="Template">
      <ControlTemplate>
        <Border x:Name="PART_Root"
                Background="{TemplateBinding Background}"
                BorderBrush="{TemplateBinding BorderBrush}"
                BorderThickness="{TemplateBinding BorderThickness}"
"""
            + "\n                CornerRadius=\"{TemplateBinding CornerRadius}\"" + sh + ">\n"
            + """
          <Panel>
            <!-- State layer. Sits under the content, over the fill. -->
            <Border x:Name="PART_StateLayer"
                    CornerRadius="{TemplateBinding CornerRadius}"
                    Background="Transparent" />
            <ContentPresenter x:Name="PART_ContentPresenter"
                              Content="{TemplateBinding Content}"
                              ContentTemplate="{TemplateBinding ContentTemplate}"
                              Foreground="{TemplateBinding Foreground}"
                              Padding="{TemplateBinding Padding}"
                              HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
                              VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}" />
          </Panel>
        </Border>
      </ControlTemplate>
    </Setter>
"""
            + "\n";
    }

    private const string Common = """
    <Setter Property="CornerRadius" Value="{DynamicResource FiliCornerRadius}" />
    <Setter Property="MinWidth" Value="64" />
    <Setter Property="FontFamily" Value="{DynamicResource FiliFontFamily}" />
    <Setter Property="FontSize" Value="{DynamicResource FiliButtonFontSize}" />
    <Setter Property="FontWeight" Value="Medium" />
    <Setter Property="LetterSpacing" Value="{DynamicResource FiliButtonLetterSpacing}" />
    <Setter Property="HorizontalContentAlignment" Value="Center" />
    <Setter Property="VerticalContentAlignment" Value="Center" />
    <Setter Property="Cursor" Value="Hand" />

""";

    // ---------------------------------------------------------------------------------------
    // Button.axaml
    // ---------------------------------------------------------------------------------------

    private static string Header => """
<!--
  Button: MudButton. Transcribed from _button.scss and MudButton.razor.cs.

  Three kinds of class, combined the way MudButton's parameters are:

    Variant   text (the default - MudButton.Variant defaults to Variant.Text), outlined, filled
    Color     none (Color.Default), primary, secondary, tertiary, info, success, warning, error,
              dark, inherit
    Size      none (Size.Medium), small, large

    <Button Content="Learn more" />                        text, default colour
    <Button Classes="primary" Content="Learn more" />      text, primary
    <Button Classes="outlined error" Content="Delete" />   outlined, error
    <Button Classes="filled primary" Content="Save" />     filled, primary
    <Button Classes="filled success small" Content="OK" /> filled, success, small

  A colour class is ONLY a colour, as Color is in MudBlazor. `primary` on its own is a primary
  TEXT button; the fill comes from `filled`. Each variant follows one rule for every colour:

    text      colour as text; hover, focus and press tint with {color}-hover (the colour at 6%)
    outlined  the same, plus a 1px line in the colour (BorderOpacity is 1.0, so it IS the colour)
    filled    colour as fill, {color}-text on it; hover, focus and press switch the fill to
              {color}-darken, and elevation goes 2 -> 4 (hover, focus) -> 8 (press)

  With no colour, text and outlined use text-primary (and so does outlined's line), tinting with
  action-default-hover. A filled button with no colour is grey: action-default-hover as the
  fill, action-disabled-background on hover.

  :active and :focus-visible share the hover value in _button.scss, so press is not a stronger
  tint here either. MudBlazor's extra press feedback is the ripple, the part with no Avalonia
  primitive: an animated, clipped ellipse driven from pointer position.

""" + "\n" + GeneratedNote + """

  Order inside each theme is load-bearing: defaults, then colours, then sizes, then disabled.
  Of two styles matching the same element, the later one wins - so a colour beats the default
  tint, and disabled beats everything.
-->
<ResourceDictionary xmlns="https://github.com/avaloniaui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">


""";

    private static string GeneratedNote => """
  GENERATED by ButtonThemeGenerator (tst/Fili.MudAvalonia.Theme.UnitTests/Generation) from one
  list of colours, so every colour follows exactly the same rules. Do not hand-edit one colour's
  block: change the generator, then rewrite this file with FILI_REGENERATE=1 (GeneratedThemeTests).

""";

    private static string TextTheme()
    {
        var o = new StringBuilder();
        o.Append("""
  <!-- Text: `.mud-button-text`. No fill, no elevation, ever. -->
  <ControlTheme x:Key="FiliTextButton" TargetType="Button">
    <Setter Property="Background" Value="Transparent" />
    <Setter Property="Foreground" Value="{DynamicResource FiliTextPrimaryBrush}" />
    <Setter Property="BorderBrush" Value="Transparent" />
    <Setter Property="BorderThickness" Value="0" />
    <Setter Property="Padding" Value="8,6" />

""");
        o.Append(Common).Append(Template(false));
        o.Append("""

    <!-- No colour: action-default-hover. Keyboard focus paints the same tint - that IS the
         affordance in MudBlazor, whose _reset.scss drops the browser focus ring. -->

""");
        o.Append(ButtonStates("", "PART_StateLayer", "Background", Res("FiliActionDefaultHoverBrush"))).Append('\n');

        foreach (var c in Colours)
        {
            o.Append(Style($"^.{c.ToLowerInvariant()}", ("Foreground", Res($"Fili{c}Brush"))));
            o.Append(ButtonStates($".{c.ToLowerInvariant()}", "PART_StateLayer", "Background", Res($"Fili{c}HoverBrush")));
        }

        o.Append("""

    <!-- Color.Inherit: `color: inherit`. Bound to the parent's inherited text colour, because a
         ControlTheme setter cannot withdraw its own Foreground and fall back to inheriting. -->

""");
        o.Append(Style("^.inherit", ("Foreground", "{Binding $parent[Control].(TextElement.Foreground)}")));
        o.Append("\n    <!-- `.mud-button-text-size-*`: 4px 5px / 8px 11px at 0.8125rem / 0.9375rem. -->\n");
        o.Append(Sizes("5,4", "11,8")).Append('\n');
        o.Append(Style("^:disabled /template/ ContentPresenter#PART_ContentPresenter", ("Foreground", Res("FiliActionDisabledBrush"))));
        o.Append(Style("^:disabled /template/ Border#PART_StateLayer", ("Background", "Transparent")));
        o.Append("  </ControlTheme>\n\n");
        return o.ToString();
    }

    private static string OutlinedTheme()
    {
        var o = new StringBuilder();
        o.Append("""
  <!--
    Outlined: `.mud-button-outlined`. The text button plus a 1px line, at 5px 15px so the line
    does not grow the button. The line is text-primary at BorderOpacity, which Palette.cs sets to
    1.0 - a hard line in the text colour, not the faint input outline.
  -->
  <ControlTheme x:Key="FiliOutlinedButton" TargetType="Button" BasedOn="{StaticResource FiliTextButton}">
    <Setter Property="BorderBrush" Value="{DynamicResource FiliTextPrimaryBrush}" />
    <Setter Property="BorderThickness" Value="1" />
    <Setter Property="Padding" Value="15,5" />


""");
        foreach (var c in Colours)
        {
            o.Append(Style($"^.{c.ToLowerInvariant()}", ("BorderBrush", Res($"Fili{c}Brush"))));
        }

        o.Append("\n    <!-- `.mud-button-outlined-inherit`: `border-color: currentColor`. -->\n");
        o.Append(Style("^.inherit", ("BorderBrush", "{Binding $self.Foreground}")));
        o.Append("\n    <!-- `.mud-button-outlined-size-*`: 3px 9px / 7px 21px. -->\n");
        o.Append(Sizes("9,3", "21,7")).Append('\n');
        o.Append(Style("^:disabled /template/ Border#PART_Root", ("BorderBrush", Res("FiliActionDisabledBackgroundBrush"))));
        o.Append("  </ControlTheme>\n\n");
        return o.ToString();
    }

    private static string FilledTheme()
    {
        var o = new StringBuilder();
        o.Append("""
  <!--
    Filled: `.mud-button-filled`. The elevation change across rest -> hover -> press is the one
    thing a style on Button cannot do, because Button has no BoxShadow - only the Border inside
    its template does. The three shadows are the layers _button.scss spells out, which are
    FiliElevation2, 4 and 8 exactly.
  -->
  <ControlTheme x:Key="FiliFilledButton" TargetType="Button">
    <Setter Property="Background" Value="{DynamicResource FiliActionDefaultHoverBrush}" />
    <Setter Property="Foreground" Value="{DynamicResource FiliTextPrimaryBrush}" />
    <Setter Property="BorderBrush" Value="Transparent" />
    <Setter Property="BorderThickness" Value="0" />
    <Setter Property="Padding" Value="16,6" />

""");
        o.Append(Common).Append(Template(true)).Append('\n');
        o.Append(Style("^:pointerover /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation4"))));
        o.Append(Style("^:focus-visible /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation4"))));
        o.Append(Style("^:pressed /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation8"))));
        o.Append("\n    <!-- No colour: grey, going to action-disabled-background. -->\n");
        o.Append(ButtonStates("", "PART_Root", "Background", Res("FiliActionDisabledBackgroundBrush"))).Append('\n');

        foreach (var c in Colours)
        {
            o.Append(Style($"^.{c.ToLowerInvariant()}", ("Background", Res($"Fili{c}Brush")), ("Foreground", Res($"Fili{c}ContrastTextBrush"))));
            o.Append(ButtonStates($".{c.ToLowerInvariant()}", "PART_Root", "Background", Res($"Fili{c}DarkenBrush")));
        }

        o.Append("""

    <!-- `.mud-button-color-inherit`: the text inherits and the grey fill stays, as in MudBlazor,
         which generates no filled-inherit class. -->

""");
        o.Append(Style("^.inherit", ("Foreground", "{Binding $parent[Control].(TextElement.Foreground)}")));
        o.Append("\n    <!-- `.mud-button-filled-size-*`: 4px 10px / 8px 22px. -->\n");
        o.Append(Sizes("10,4", "22,8"));
        o.Append("\n    <!-- Disabled drops to the ground: no shadow at all, not a dimmed one. -->\n");
        o.Append(Style("^:disabled /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation0")), ("Background", Res("FiliActionDisabledBackgroundBrush"))));
        o.Append(Style("^:disabled /template/ ContentPresenter#PART_ContentPresenter", ("Foreground", Res("FiliActionDisabledBrush"))));
        o.Append("  </ControlTheme>\n\n");
        return o.ToString();
    }

    private const string Footer = """
  <!--
    MudButton defaults to Variant.Text and Color.Default, so an unclassed Button is the text one in
    text-primary. `outlined` and `filled` switch the theme (FiliTheme.axaml); colour and size
    classes work inside whichever theme is active.
  -->
  <ControlTheme x:Key="{x:Type Button}" TargetType="Button" BasedOn="{StaticResource FiliTextButton}" />

</ResourceDictionary>

""";

    // ---------------------------------------------------------------------------------------
    // SplitButton.axaml region: MudButtonGroup, from _buttongroup.scss.
    //
    // Every rule sets one of three SplitButton properties - Foreground, Background (both halves'
    // fill) and BorderBrush (the line: separator, and outline when outlined) - or lights a half
    // through `/template/ Button`, because a selector may cross only one /template/ boundary.
    // ---------------------------------------------------------------------------------------

    /// <summary>
    /// Hover and press on either half, keyboard focus on the group (lights the main half), and an
    /// open flyout (lights the chevron half). _buttongroup.scss gives them one value.
    /// </summary>
    private static string SplitStates(string prefix, params (string, string)[] setters) =>
        Style($"^{prefix} /template/ Button:pointerover", setters)
        + Style($"^{prefix} /template/ Button:pressed", setters)
        + Style($"^{prefix}:focus-visible /template/ Button#PART_PrimaryButton", setters)
        + Style($"^{prefix}[Tag=flyout-open] /template/ Button#PART_SecondaryButton", setters);

    private static string SplitRegion()
    {
        var o = new StringBuilder();
        o.Append("    <!-- Text, no colour: action-default-hover on the half under the pointer. -->\n");
        o.Append(SplitStates("", ("BorderBrush", Res("FiliActionDefaultHoverBrush"))));
        o.Append("\n    <!-- Text and outlined colours: the label, the line, and the hover tint. -->\n");

        foreach (var c in Colours)
        {
            o.Append(Style($"^.{c.ToLowerInvariant()}", ("Foreground", Res($"Fili{c}Brush")), ("BorderBrush", Res($"Fili{c}Brush"))));
            o.Append(SplitStates($".{c.ToLowerInvariant()}", ("BorderBrush", Res($"Fili{c}HoverBrush"))));
        }

        o.Append("\n    <!-- Color.Inherit: the surrounding text colour, for the label and the line. -->\n");
        o.Append(Style("^.inherit", ("Foreground", "{Binding $parent[Control].(TextElement.Foreground)}"), ("BorderBrush", "{Binding $self.Foreground}")));
        o.Append("\n    <!-- `.mud-button-group-text-size-*`. -->\n");
        o.Append(Sizes("5,4", "11,8"));
        o.Append("""

    <!-- Outlined: each segment's own 1px border in the line colour, 5px 15px. Avalonia draws one
         outline round both halves plus the separator between them, which is the same picture. -->

""");
        o.Append(Style("^.outlined", ("BorderThickness", "1"), ("Padding", "15,5")));
        o.Append(Style("^.outlined.small", ("Padding", "9,3"), ("FontSize", "13")));
        o.Append(Style("^.outlined.large", ("Padding", "21,7"), ("FontSize", "15")));
        o.Append("""

    <!-- Filled: action-default-hover as the fill, `divider` between the segments, elevation 2
         lifting to 4. A coloured fill divides with {color}-lighten and darkens on hover. -->

""");
        o.Append(Style("^.filled", ("Background", Res("FiliActionDefaultHoverBrush")), ("Foreground", Res("FiliTextPrimaryBrush")), ("BorderBrush", Res("FiliDividerBrush")), ("Padding", "16,6")));
        o.Append(Style("^.filled /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation2"))));
        o.Append(Style("^.filled:pointerover /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation4"))));
        o.Append(Style("^.filled:focus-visible /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation4"))));
        o.Append(SplitStates(".filled", ("Background", Res("FiliActionDisabledBackgroundBrush")), ("BorderBrush", "Transparent")));

        foreach (var c in Colours)
        {
            o.Append(Style($"^.filled.{c.ToLowerInvariant()}", ("Background", Res($"Fili{c}Brush")), ("Foreground", Res($"Fili{c}ContrastTextBrush")), ("BorderBrush", Res($"Fili{c}LightenBrush"))));
            o.Append(SplitStates($".filled.{c.ToLowerInvariant()}", ("Background", Res($"Fili{c}DarkenBrush"))));
        }

        o.Append(Style("^.filled.small", ("Padding", "10,4"), ("FontSize", "13")));
        o.Append(Style("^.filled.large", ("Padding", "22,8"), ("FontSize", "15")));
        o.Append("\n    <!-- Disabled last, so it beats every colour. -->\n");
        o.Append(Style("^:disabled", ("Foreground", Res("FiliActionDisabledBrush")), ("BorderBrush", Res("FiliActionDisabledBackgroundBrush"))));
        o.Append(Style("^:disabled /template/ Button", ("BorderBrush", "Transparent")));
        o.Append(Style("^.filled:disabled", ("Background", Res("FiliActionDisabledBackgroundBrush"))));
        o.Append(Style("^.filled:disabled /template/ Border#PART_Root", ("BoxShadow", Res("FiliElevation0"))));
        return o.ToString();
    }

    // ---------------------------------------------------------------------------------------
    // FiliTheme.axaml region: MudText's Color, one class per palette colour.
    // ---------------------------------------------------------------------------------------

    private static string TextBlockRegion() =>
        string.Concat(Colours.Select(c =>
            $"  <Style Selector=\"TextBlock.{c.ToLowerInvariant()}\">\n"
            + $"    <Setter Property=\"Foreground\" Value=\"{Res($"Fili{c}Brush")}\" />\n"
            + "  </Style>\n"));
}
